### ISSUE TITLE
Intégration fluxbb

### ISSUE THREAD

**Issue by oneil4** [DiemenDesign/summernote-themes#1]
Hi, thank for your time.

Is possible use whit fluxbb ? Or not ? 

The good idea :
Add one boutton for upload image on imgur ( ckeditor capable whit plugin) and past the image direct on the textarea :) 

Thank you

Just is possible use whit fluxbb platform ? Or punbb

**Comment by DennisSuitters** [comment]
You would be better opening your issue on the main project, then someone who may have used your chosen system can help, or make suggestions to help you.
